print(2 * 3)
print(type(2 * 3))
print((3 * 3 + 8) / 3)
print(type((3 * 3 + 8) / 3))
print(8 // 3)
print(type(8 // 3))
print(8 % 3)
print(type(8 % 3))
print(5 ** 2)
print(type(5 ** 2))
print('Hello' + 'World')
print(type('Hello' + 'World'))
a = "Yesterday All my troubles seemed so far away"
b = 'Now it looks as though here to stay'
print(a[:10])
print(a[2:12])
print(a[-10:])
print(a[::-1])
print(a[::2])
print(a[1::2])
a = int(input("Введите первое число: "))
c = int(input("Введите второе число: "))
print(a + c)